// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enhzqovqksjxzfcrbctg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuaHpxb3Zxa3NqeHpmY3JiY3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNTAxNzMsImV4cCI6MjA1NjkyNjE3M30.3bATVRoG4Cm5v0FXxl1rQt3AC75nA8-ZJ0NavoOVCww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);